
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import java.util.function.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\061\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\011\000\002\003\004" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\003\000\002\003\007\000\002" +
    "\003\003\000\002\013\003\000\002\013\003\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\011\005" +
    "\000\002\011\005\000\002\011\003\000\002\011\004\000" +
    "\002\011\003\000\002\011\003\000\002\011\005\000\002" +
    "\011\006\000\002\017\005\000\002\017\003\000\002\017" +
    "\002\000\002\014\005\000\002\014\005\000\002\014\005" +
    "\000\002\014\005\000\002\014\005\000\002\014\005\000" +
    "\002\014\003\000\002\014\003\000\002\014\005\000\002" +
    "\012\005\000\002\007\005\000\002\004\007\000\002\004" +
    "\011\000\002\005\007\000\002\006\013\000\002\015\004" +
    "\000\002\015\003\000\002\016\006\000\002\016\005\000" +
    "\002\010\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\040\004\007\006\030\012\016\014\015\016" +
    "\011\021\014\023\010\024\034\025\031\027\013\041\012" +
    "\042\027\043\026\044\024\045\005\001\002\000\052\002" +
    "\ufffa\004\ufffa\006\ufffa\012\ufffa\014\ufffa\015\ufffa\016\ufffa" +
    "\021\ufffa\022\ufffa\023\ufffa\024\ufffa\025\ufffa\027\ufffa\030" +
    "\ufffa\031\ufffa\041\ufffa\042\ufffa\043\ufffa\044\ufffa\045\ufffa" +
    "\001\002\000\034\004\uffea\005\uffea\006\uffea\007\uffea\010" +
    "\uffea\016\161\032\uffea\033\uffea\034\uffea\035\uffea\036\uffea" +
    "\037\uffea\040\057\001\002\000\040\004\ufff4\005\067\006" +
    "\070\007\072\010\071\013\ufff4\017\ufff4\020\ufff4\026\ufff4" +
    "\032\ufff4\033\ufff4\034\111\035\112\036\113\037\110\001" +
    "\002\000\052\002\ufff5\004\ufff5\006\ufff5\012\ufff5\014\ufff5" +
    "\015\ufff5\016\ufff5\021\ufff5\022\ufff5\023\ufff5\024\ufff5\025" +
    "\ufff5\027\ufff5\030\ufff5\031\ufff5\041\ufff5\042\ufff5\043\ufff5" +
    "\044\ufff5\045\ufff5\001\002\000\004\012\155\001\002\000" +
    "\026\006\030\012\016\016\011\017\uffe5\020\uffe5\041\012" +
    "\042\027\043\026\044\024\045\043\001\002\000\020\004" +
    "\uffde\013\uffde\017\uffde\020\uffde\026\uffde\032\uffde\033\uffde" +
    "\001\002\000\004\012\131\001\002\000\004\012\123\001" +
    "\002\000\040\004\007\006\030\012\016\014\015\016\011" +
    "\021\014\023\010\024\034\025\031\027\013\041\012\042" +
    "\027\043\026\044\024\045\005\001\002\000\022\006\030" +
    "\012\016\016\011\041\012\042\027\043\026\044\024\045" +
    "\043\001\002\000\052\002\ufff7\004\ufff7\006\ufff7\012\ufff7" +
    "\014\ufff7\015\ufff7\016\ufff7\021\ufff7\022\ufff7\023\ufff7\024" +
    "\ufff7\025\ufff7\027\ufff7\030\ufff7\031\ufff7\041\ufff7\042\ufff7" +
    "\043\ufff7\044\ufff7\045\ufff7\001\002\000\020\004\ufff3\013" +
    "\ufff3\017\ufff3\020\ufff3\026\ufff3\032\ufff3\033\ufff3\001\002" +
    "\000\004\004\104\001\002\000\042\002\102\004\007\006" +
    "\030\012\016\014\015\016\011\021\014\023\010\024\034" +
    "\025\031\027\013\041\012\042\027\043\026\044\024\045" +
    "\005\001\002\000\010\004\101\032\050\033\047\001\002" +
    "\000\040\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\013" +
    "\uffeb\017\uffeb\020\uffeb\026\uffeb\032\uffeb\033\uffeb\034\uffeb" +
    "\035\uffeb\036\uffeb\037\uffeb\001\002\000\052\002\ufff8\004" +
    "\ufff8\006\ufff8\012\ufff8\014\ufff8\015\ufff8\016\ufff8\021\ufff8" +
    "\022\ufff8\023\ufff8\024\ufff8\025\ufff8\027\ufff8\030\ufff8\031" +
    "\ufff8\041\ufff8\042\ufff8\043\ufff8\044\ufff8\045\ufff8\001\002" +
    "\000\040\004\uffed\005\uffed\006\uffed\007\uffed\010\uffed\013" +
    "\uffed\017\uffed\020\uffed\026\uffed\032\uffed\033\uffed\034\uffed" +
    "\035\uffed\036\uffed\037\uffed\001\002\000\020\004\uffdd\013" +
    "\uffdd\017\uffdd\020\uffdd\026\uffdd\032\uffdd\033\uffdd\001\002" +
    "\000\016\006\030\012\065\016\011\043\026\044\024\045" +
    "\043\001\002\000\004\012\061\001\002\000\052\002\ufffb" +
    "\004\ufffb\006\ufffb\012\ufffb\014\ufffb\015\ufffb\016\ufffb\021" +
    "\ufffb\022\ufffb\023\ufffb\024\ufffb\025\ufffb\027\ufffb\030\ufffb" +
    "\031\ufffb\041\ufffb\042\ufffb\043\ufffb\044\ufffb\045\ufffb\001" +
    "\002\000\052\002\ufff9\004\ufff9\006\ufff9\012\ufff9\014\ufff9" +
    "\015\ufff9\016\ufff9\021\ufff9\022\ufff9\023\ufff9\024\ufff9\025" +
    "\ufff9\027\ufff9\030\ufff9\031\ufff9\041\ufff9\042\ufff9\043\ufff9" +
    "\044\ufff9\045\ufff9\001\002\000\004\012\036\001\002\000" +
    "\044\002\uffff\004\uffff\006\uffff\012\uffff\014\uffff\015\uffff" +
    "\016\uffff\021\uffff\023\uffff\024\uffff\025\uffff\027\uffff\041" +
    "\uffff\042\uffff\043\uffff\044\uffff\045\uffff\001\002\000\004" +
    "\045\037\001\002\000\004\040\057\001\002\000\004\004" +
    "\041\001\002\000\022\006\030\012\016\016\011\041\012" +
    "\042\027\043\026\044\024\045\043\001\002\000\010\004" +
    "\053\032\050\033\047\001\002\000\042\004\uffea\005\uffea" +
    "\006\uffea\007\uffea\010\uffea\013\uffea\016\044\017\uffea\020" +
    "\uffea\026\uffea\032\uffea\033\uffea\034\uffea\035\uffea\036\uffea" +
    "\037\uffea\001\002\000\022\006\030\012\016\016\011\041" +
    "\012\042\027\043\026\044\024\045\043\001\002\000\010" +
    "\017\046\032\050\033\047\001\002\000\040\004\uffe8\005" +
    "\uffe8\006\uffe8\007\uffe8\010\uffe8\013\uffe8\017\uffe8\020\uffe8" +
    "\026\uffe8\032\uffe8\033\uffe8\034\uffe8\035\uffe8\036\uffe8\037" +
    "\uffe8\001\002\000\022\006\030\012\016\016\011\041\012" +
    "\042\027\043\026\044\024\045\043\001\002\000\022\006" +
    "\030\012\016\016\011\041\012\042\027\043\026\044\024" +
    "\045\043\001\002\000\020\004\uffe4\013\uffe4\017\uffe4\020" +
    "\uffe4\026\uffe4\032\uffe4\033\uffe4\001\002\000\020\004\uffe3" +
    "\013\uffe3\017\uffe3\020\uffe3\026\uffe3\032\uffe3\033\uffe3\001" +
    "\002\000\004\045\037\001\002\000\004\013\055\001\002" +
    "\000\040\004\007\006\030\012\016\014\015\016\011\021" +
    "\014\023\010\024\034\025\031\027\013\041\012\042\027" +
    "\043\026\044\024\045\005\001\002\000\052\002\uffd6\004" +
    "\uffd6\006\uffd6\012\uffd6\014\uffd6\015\uffd6\016\uffd6\021\uffd6" +
    "\022\uffd6\023\uffd6\024\uffd6\025\uffd6\027\uffd6\030\uffd6\031" +
    "\uffd6\041\uffd6\042\uffd6\043\uffd6\044\uffd6\045\uffd6\001\002" +
    "\000\022\006\030\012\016\016\011\041\012\042\027\043" +
    "\026\044\024\045\043\001\002\000\012\004\uffdb\013\uffdb" +
    "\032\050\033\047\001\002\000\022\006\030\012\016\016" +
    "\011\041\012\042\027\043\026\044\024\045\043\001\002" +
    "\000\010\013\063\032\050\033\047\001\002\000\004\004" +
    "\064\001\002\000\052\002\ufff6\004\ufff6\006\ufff6\012\ufff6" +
    "\014\ufff6\015\ufff6\016\ufff6\021\ufff6\022\ufff6\023\ufff6\024" +
    "\ufff6\025\ufff6\027\ufff6\030\ufff6\031\ufff6\041\ufff6\042\ufff6" +
    "\043\ufff6\044\ufff6\045\ufff6\001\002\000\016\006\030\012" +
    "\065\016\011\043\026\044\024\045\043\001\002\000\040" +
    "\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec\013\uffec\017" +
    "\uffec\020\uffec\026\uffec\032\uffec\033\uffec\034\uffec\035\uffec" +
    "\036\uffec\037\uffec\001\002\000\016\006\030\012\065\016" +
    "\011\043\026\044\024\045\043\001\002\000\016\006\030" +
    "\012\065\016\011\043\026\044\024\045\043\001\002\000" +
    "\016\006\030\012\065\016\011\043\026\044\024\045\043" +
    "\001\002\000\016\006\030\012\065\016\011\043\026\044" +
    "\024\045\043\001\002\000\040\004\ufff0\005\ufff0\006\ufff0" +
    "\007\ufff0\010\ufff0\013\ufff0\017\ufff0\020\ufff0\026\ufff0\032" +
    "\ufff0\033\ufff0\034\ufff0\035\ufff0\036\ufff0\037\ufff0\001\002" +
    "\000\040\004\uffef\005\uffef\006\uffef\007\uffef\010\uffef\013" +
    "\uffef\017\uffef\020\uffef\026\uffef\032\uffef\033\uffef\034\uffef" +
    "\035\uffef\036\uffef\037\uffef\001\002\000\040\004\ufff1\005" +
    "\ufff1\006\ufff1\007\072\010\071\013\ufff1\017\ufff1\020\ufff1" +
    "\026\ufff1\032\ufff1\033\ufff1\034\ufff1\035\ufff1\036\ufff1\037" +
    "\ufff1\001\002\000\040\004\ufff2\005\ufff2\006\ufff2\007\072" +
    "\010\071\013\ufff2\017\ufff2\020\ufff2\026\ufff2\032\ufff2\033" +
    "\ufff2\034\ufff2\035\ufff2\036\ufff2\037\ufff2\001\002\000\014" +
    "\005\067\006\070\007\072\010\071\013\100\001\002\000" +
    "\040\004\uffee\005\uffee\006\uffee\007\uffee\010\uffee\013\uffee" +
    "\017\uffee\020\uffee\026\uffee\032\uffee\033\uffee\034\uffee\035" +
    "\uffee\036\uffee\037\uffee\001\002\000\052\002\ufffc\004\ufffc" +
    "\006\ufffc\012\ufffc\014\ufffc\015\ufffc\016\ufffc\021\ufffc\022" +
    "\ufffc\023\ufffc\024\ufffc\025\ufffc\027\ufffc\030\ufffc\031\ufffc" +
    "\041\ufffc\042\ufffc\043\ufffc\044\ufffc\045\ufffc\001\002\000" +
    "\004\002\001\001\002\000\044\002\000\004\000\006\000" +
    "\012\000\014\000\015\000\016\000\021\000\023\000\024" +
    "\000\025\000\027\000\041\000\042\000\043\000\044\000" +
    "\045\000\001\002\000\052\002\ufffe\004\ufffe\006\ufffe\012" +
    "\ufffe\014\ufffe\015\ufffe\016\ufffe\021\ufffe\022\ufffe\023\ufffe" +
    "\024\ufffe\025\ufffe\027\ufffe\030\ufffe\031\ufffe\041\ufffe\042" +
    "\ufffe\043\ufffe\044\ufffe\045\ufffe\001\002\000\010\013\120" +
    "\032\ufff3\033\ufff3\001\002\000\030\005\067\006\070\007" +
    "\072\010\071\013\100\032\ufff4\033\ufff4\034\111\035\112" +
    "\036\113\037\110\001\002\000\006\032\050\033\047\001" +
    "\002\000\016\006\030\012\065\016\011\043\026\044\024" +
    "\045\043\001\002\000\016\006\030\012\065\016\011\043" +
    "\026\044\024\045\043\001\002\000\016\006\030\012\065" +
    "\016\011\043\026\044\024\045\043\001\002\000\016\006" +
    "\030\012\065\016\011\043\026\044\024\045\043\001\002" +
    "\000\030\004\uffe0\005\067\006\070\007\072\010\071\013" +
    "\uffe0\017\uffe0\020\uffe0\026\uffe0\032\uffe0\033\uffe0\001\002" +
    "\000\030\004\uffe1\005\067\006\070\007\072\010\071\013" +
    "\uffe1\017\uffe1\020\uffe1\026\uffe1\032\uffe1\033\uffe1\001\002" +
    "\000\030\004\uffe2\005\067\006\070\007\072\010\071\013" +
    "\uffe2\017\uffe2\020\uffe2\026\uffe2\032\uffe2\033\uffe2\001\002" +
    "\000\030\004\uffdf\005\067\006\070\007\072\010\071\013" +
    "\uffdf\017\uffdf\020\uffdf\026\uffdf\032\uffdf\033\uffdf\001\002" +
    "\000\020\004\uffdc\013\uffdc\017\uffdc\020\uffdc\026\uffdc\032" +
    "\uffdc\033\uffdc\001\002\000\042\004\007\006\030\012\016" +
    "\014\015\015\122\016\011\021\014\023\010\024\034\025" +
    "\031\027\013\041\012\042\027\043\026\044\024\045\005" +
    "\001\002\000\052\002\uffda\004\uffda\006\uffda\012\uffda\014" +
    "\uffda\015\uffda\016\uffda\021\uffda\022\uffda\023\uffda\024\uffda" +
    "\025\uffda\027\uffda\030\uffda\031\uffda\041\uffda\042\uffda\043" +
    "\uffda\044\uffda\045\uffda\001\002\000\022\006\030\012\016" +
    "\016\011\041\012\042\027\043\026\044\024\045\043\001" +
    "\002\000\010\013\125\032\050\033\047\001\002\000\040" +
    "\004\007\006\030\012\016\014\015\016\011\021\014\023" +
    "\010\024\034\025\031\027\013\041\012\042\027\043\026" +
    "\044\024\045\005\001\002\000\052\002\uffd9\004\uffd9\006" +
    "\uffd9\012\uffd9\014\uffd9\015\uffd9\016\uffd9\021\uffd9\022\127" +
    "\023\uffd9\024\uffd9\025\uffd9\027\uffd9\030\uffd9\031\uffd9\041" +
    "\uffd9\042\uffd9\043\uffd9\044\uffd9\045\uffd9\001\002\000\040" +
    "\004\007\006\030\012\016\014\015\016\011\021\014\023" +
    "\010\024\034\025\031\027\013\041\012\042\027\043\026" +
    "\044\024\045\005\001\002\000\052\002\uffd8\004\uffd8\006" +
    "\uffd8\012\uffd8\014\uffd8\015\uffd8\016\uffd8\021\uffd8\022\uffd8" +
    "\023\uffd8\024\uffd8\025\uffd8\027\uffd8\030\uffd8\031\uffd8\041" +
    "\uffd8\042\uffd8\043\uffd8\044\uffd8\045\uffd8\001\002\000\022" +
    "\006\030\012\016\016\011\041\012\042\027\043\026\044" +
    "\024\045\043\001\002\000\010\013\133\032\050\033\047" +
    "\001\002\000\004\014\134\001\002\000\006\030\140\031" +
    "\135\001\002\000\004\026\146\001\002\000\010\015\uffd4" +
    "\030\uffd4\031\uffd4\001\002\000\010\015\145\030\140\031" +
    "\135\001\002\000\022\006\030\012\016\016\011\041\012" +
    "\042\027\043\026\044\024\045\043\001\002\000\010\026" +
    "\142\032\050\033\047\001\002\000\040\004\007\006\030" +
    "\012\016\014\015\016\011\021\014\023\010\024\034\025" +
    "\031\027\013\041\012\042\027\043\026\044\024\045\005" +
    "\001\002\000\010\015\uffd3\030\uffd3\031\uffd3\001\002\000" +
    "\010\015\uffd5\030\uffd5\031\uffd5\001\002\000\052\002\uffd1" +
    "\004\uffd1\006\uffd1\012\uffd1\014\uffd1\015\uffd1\016\uffd1\021" +
    "\uffd1\022\uffd1\023\uffd1\024\uffd1\025\uffd1\027\uffd1\030\uffd1" +
    "\031\uffd1\041\uffd1\042\uffd1\043\uffd1\044\uffd1\045\uffd1\001" +
    "\002\000\040\004\007\006\030\012\016\014\015\016\011" +
    "\021\014\023\010\024\034\025\031\027\013\041\012\042" +
    "\027\043\026\044\024\045\005\001\002\000\010\015\uffd2" +
    "\030\uffd2\031\uffd2\001\002\000\006\017\153\020\152\001" +
    "\002\000\012\017\uffe6\020\uffe6\032\050\033\047\001\002" +
    "\000\022\006\030\012\016\016\011\041\012\042\027\043" +
    "\026\044\024\045\043\001\002\000\040\004\uffe9\005\uffe9" +
    "\006\uffe9\007\uffe9\010\uffe9\013\uffe9\017\uffe9\020\uffe9\026" +
    "\uffe9\032\uffe9\033\uffe9\034\uffe9\035\uffe9\036\uffe9\037\uffe9" +
    "\001\002\000\012\017\uffe7\020\uffe7\032\050\033\047\001" +
    "\002\000\022\006\030\012\016\016\011\041\012\042\027" +
    "\043\026\044\024\045\043\001\002\000\010\013\157\032" +
    "\050\033\047\001\002\000\040\004\007\006\030\012\016" +
    "\014\015\016\011\021\014\023\010\024\034\025\031\027" +
    "\013\041\012\042\027\043\026\044\024\045\005\001\002" +
    "\000\052\002\uffd7\004\uffd7\006\uffd7\012\uffd7\014\uffd7\015" +
    "\uffd7\016\uffd7\021\uffd7\022\uffd7\023\uffd7\024\uffd7\025\uffd7" +
    "\027\uffd7\030\uffd7\031\uffd7\041\uffd7\042\uffd7\043\uffd7\044" +
    "\uffd7\045\uffd7\001\002\000\022\006\030\012\016\016\011" +
    "\041\012\042\027\043\026\044\024\045\043\001\002\000" +
    "\010\017\163\032\050\033\047\001\002\000\032\004\uffe8" +
    "\005\uffe8\006\uffe8\007\uffe8\010\uffe8\032\uffe8\033\uffe8\034" +
    "\uffe8\035\uffe8\036\uffe8\037\uffe8\040\164\001\002\000\022" +
    "\006\030\012\016\016\011\041\012\042\027\043\026\044" +
    "\024\045\043\001\002\000\010\004\166\032\050\033\047" +
    "\001\002\000\052\002\ufffd\004\ufffd\006\ufffd\012\ufffd\014" +
    "\ufffd\015\ufffd\016\ufffd\021\ufffd\022\ufffd\023\ufffd\024\ufffd" +
    "\025\ufffd\027\ufffd\030\ufffd\031\ufffd\041\ufffd\042\ufffd\043" +
    "\ufffd\044\ufffd\045\ufffd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\164\000\030\002\021\003\034\004\031\005\003\006" +
    "\032\007\016\010\024\011\005\012\020\013\022\014\017" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\011\005" +
    "\013\150\014\017\017\147\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\030\002\120\003\034" +
    "\004\031\005\003\006\032\007\016\010\024\011\005\012" +
    "\020\013\022\014\017\001\001\000\010\011\105\013\106" +
    "\014\104\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\026\003\102\004\031\005\003\006\032" +
    "\007\016\010\024\011\005\012\020\013\022\014\017\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\011\065\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\012\037\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\011\005" +
    "\013\041\014\017\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\011\005\013\044\014\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\011\005\013\051\014" +
    "\017\001\001\000\010\011\005\013\050\014\017\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\012\053\001" +
    "\001\000\002\001\001\000\026\003\055\004\031\005\003" +
    "\006\032\007\016\010\024\011\005\012\020\013\022\014" +
    "\017\001\001\000\002\001\001\000\010\011\005\013\057" +
    "\014\017\001\001\000\002\001\001\000\010\011\005\013" +
    "\061\014\017\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\076\001\001\000\002\001" +
    "\001\000\004\011\075\001\001\000\004\011\074\001\001" +
    "\000\004\011\073\001\001\000\004\011\072\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\011\116\001\001\000\004\011\115\001\001\000\004" +
    "\011\114\001\001\000\004\011\113\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\003\102\004\031\005\003\006" +
    "\032\007\016\010\024\011\005\012\020\013\022\014\017" +
    "\001\001\000\002\001\001\000\010\011\005\013\123\014" +
    "\017\001\001\000\002\001\001\000\026\003\125\004\031" +
    "\005\003\006\032\007\016\010\024\011\005\012\020\013" +
    "\022\014\017\001\001\000\002\001\001\000\026\003\127" +
    "\004\031\005\003\006\032\007\016\010\024\011\005\012" +
    "\020\013\022\014\017\001\001\000\002\001\001\000\010" +
    "\011\005\013\131\014\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\136\016\135\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\016\143\001\001\000" +
    "\010\011\005\013\140\014\017\001\001\000\002\001\001" +
    "\000\026\003\142\004\031\005\003\006\032\007\016\010" +
    "\024\011\005\012\020\013\022\014\017\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\026\003" +
    "\146\004\031\005\003\006\032\007\016\010\024\011\005" +
    "\012\020\013\022\014\017\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\005\013\153" +
    "\014\017\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\011\005\013\155\014\017\001\001\000\002\001\001" +
    "\000\026\003\157\004\031\005\003\006\032\007\016\010" +
    "\024\011\005\012\020\013\022\014\017\001\001\000\002" +
    "\001\001\000\010\011\005\013\161\014\017\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\011\005\013\164" +
    "\014\017\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.next_token(); 
    }


    scanner s;
    Map<String, Object> vars = new HashMap<>();

    public parser(scanner s){ this.s = s; }

    /* --- CLASSE AUXILIAR PARA O SWITCH --- */
    static class CaseObs {
        Supplier<Object> value; 
        Runnable action;
        
        public CaseObs(Supplier<Object> val, Runnable act) {
            this.value = val;
            this.action = act;
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= stmt_list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable start_val = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // stmt_list ::= stmt_list stmt 
            {
              Runnable RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable l = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            RESULT = () -> {
                if (l != null) l.run();
                if (s != null) s.run();
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // stmt_list ::= stmt 
            {
              Runnable RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt ::= assignment_expr SEMI 
            {
              Runnable RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> a = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = () -> { a.get(); }; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt ::= WORD LBRACK any_expr RBRACK GETS any_expr SEMI 
            {
              Runnable RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int idxleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idxright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> idx = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> val = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            RESULT = () -> {
                Object listaObj = vars.get(nome);
                Object indexObj = idx.get();
                Object valor = val.get();

                if (listaObj instanceof List && indexObj instanceof Double) {
                    List<Object> lista = (List<Object>) listaObj;
                    int i = ((Double) indexObj).intValue();
                    
                    // Garante tamanho (simples) ou lança erro se for OOB
                    if (i >= 0 && i < lista.size()) {
                        lista.set(i, valor);
                    } else {
                        System.err.println("Erro: �?ndice fora dos limites ou inválido: " + i);
                    }
                } else {
                    System.err.println("Erro: Variável '" + nome + "' não é um vetor ou índice inválido.");
                }
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt ::= any_expr SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = () -> { e.get(); }; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt ::= if_stmt 
            {
              Runnable RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable i = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= while_stmt 
            {
              Runnable RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int wright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable w = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = w; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= for_stmt 
            {
              Runnable RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable f = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= switch_stmt 
            {
              Runnable RESULT =null;
		int swleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int swright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable sw = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = sw; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= block 
            {
              Runnable RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable b = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= PRINT LPAREN any_expr RPAREN SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
            RESULT = () -> System.out.println(e.get());
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // stmt ::= SEMI 
            {
              Runnable RESULT =null;
		 RESULT = () -> {}; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // any_expr ::= expr 
            {
              Supplier<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("any_expr",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // any_expr ::= bool_expr 
            {
              Supplier<Object> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Boolean> b = (Supplier<Boolean>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Object) b.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("any_expr",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= expr PLUS expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() + (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= expr MINUS expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() - (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= expr TIMES expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() * (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= expr DIV expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() / (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= LPAREN expr RPAREN 
            {
              Supplier<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= NUMBER 
            {
              Supplier<Object> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double n = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= MINUS expr 
            {
              Supplier<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> -(Double)e.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= STRING 
            {
              Supplier<Object> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr ::= WORD 
            {
              Supplier<Object> RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                RESULT = () -> {
                    Object val = vars.get(nome);
                    return (val == null) ? 0.0 : val;
                };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // expr ::= LBRACK arg_list RBRACK 
            {
              Supplier<Object> RESULT =null;
		int argsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int argsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<Supplier<Object>> args = (List<Supplier<Object>>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            RESULT = () -> {
                List<Object> novaLista = new ArrayList<>();
                for(Supplier<Object> s : args) {
                    novaLista.add(s.get());
                }
                return novaLista;
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // expr ::= WORD LBRACK any_expr RBRACK 
            {
              Supplier<Object> RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int idxleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int idxright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> idx = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            RESULT = () -> {
                Object listaObj = vars.get(nome);
                Object indexObj = idx.get();
                
                if (listaObj instanceof List && indexObj instanceof Double) {
                    List<Object> lista = (List<Object>) listaObj;
                    int i = ((Double) indexObj).intValue();
                    if (i >= 0 && i < lista.size()) {
                        return lista.get(i);
                    }
                }
                return 0.0; // Retorno padrão em caso de erro
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // arg_list ::= arg_list COMMA any_expr 
            {
              List<Supplier<Object>> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		List<Supplier<Object>> l = (List<Supplier<Object>>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            l.add(e);
            RESULT = l;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // arg_list ::= any_expr 
            {
              List<Supplier<Object>> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            List<Supplier<Object>> l = new ArrayList<>();
            l.add(e);
            RESULT = l;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // arg_list ::= 
            {
              List<Supplier<Object>> RESULT =null;
		
            RESULT = new ArrayList<>();
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // bool_expr ::= any_expr IGUAL any_expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> Objects.equals(e1.get(), e2.get()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // bool_expr ::= any_expr NOT any_expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> !Objects.equals(e1.get(), e2.get()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // bool_expr ::= expr MENOR_QUE expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() < (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // bool_expr ::= expr MAIOR_QUE expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() > (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // bool_expr ::= expr MENOR_IGUAL expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() <= (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // bool_expr ::= expr MAIOR_IGUAL expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() >= (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bool_expr ::= TRUE 
            {
              Supplier<Boolean> RESULT =null;
		 RESULT = () -> true;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bool_expr ::= FALSE 
            {
              Supplier<Boolean> RESULT =null;
		 RESULT = () -> false; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // bool_expr ::= LPAREN bool_expr RPAREN 
            {
              Supplier<Boolean> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Boolean> b = (Supplier<Boolean>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // assignment_expr ::= WORD GETS any_expr 
            {
              Supplier<Object> RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> val = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
          RESULT = () -> {
              Object v = val.get();
              vars.put(nome, v);
              return v;
          };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment_expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // block ::= LBRACE stmt_list RBRACE 
            {
              Runnable RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable l = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // if_stmt ::= IF LPAREN any_expr RPAREN stmt 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   Object val = e.get();
                   if (val instanceof Boolean && (Boolean)val) { s.run(); }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // if_stmt ::= IF LPAREN any_expr RPAREN stmt ELSE stmt 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Runnable s1 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s2 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   Object val = e.get();
                   if (val instanceof Boolean && (Boolean)val) { s1.run(); } else { s2.run(); }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // while_stmt ::= WHILE LPAREN any_expr RPAREN stmt 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   Object val = e.get();
                   while (val instanceof Boolean && (Boolean)val) {
                       s.run();
                       val = e.get();
                   }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // for_stmt ::= FOR LPAREN assignment_expr SEMI any_expr SEMI assignment_expr RPAREN stmt 
            {
              Runnable RESULT =null;
		int initleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int initright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Supplier<Object> init = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> cond = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> step = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable body = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   init.get();
                   Object val = cond.get();
                   while (val instanceof Boolean && (Boolean)val) {
                       body.run();
                       step.get();
                       val = cond.get();
                   }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // case_list ::= case_list case_item 
            {
              List<CaseObs> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<CaseObs> l = (List<CaseObs>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CaseObs i = (CaseObs)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            l.add(i);
            RESULT = l;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // case_list ::= case_item 
            {
              List<CaseObs> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CaseObs i = (CaseObs)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            List<CaseObs> l = new ArrayList<>();
            l.add(i);
            RESULT = l;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // case_item ::= CASE any_expr COLON stmt 
            {
              CaseObs RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CaseObs(e, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_item",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // case_item ::= DEFAULT COLON stmt 
            {
              CaseObs RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new CaseObs(null, s); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_item",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // switch_stmt ::= SWITCH LPAREN any_expr RPAREN LBRACE case_list RBRACE 
            {
              Runnable RESULT =null;
		int targetleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int targetright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> target = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int casesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int casesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<CaseObs> cases = (List<CaseObs>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            RESULT = () -> {
                Object valAlvo = target.get();
                boolean executou = false;

                for (CaseObs c : cases) {
                    if (c.value != null) {
                        Object valCase = c.value.get();
                        if (Objects.equals(valAlvo, valCase)) {
                            c.action.run();
                            executou = true;
                            break; 
                        }
                    }
                }

                if (!executou) {
                    for (CaseObs c : cases) {
                        if (c.value == null) {
                            c.action.run();
                            break;
                        }
                    }
                }
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("switch_stmt",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
