
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import java.util.function.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\053\000\002\002\004\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\004\000\002\003\003" +
    "\000\002\003\003\000\002\003\003\000\002\003\003\000" +
    "\002\003\003\000\002\003\007\000\002\003\003\000\002" +
    "\013\003\000\002\013\003\000\002\011\005\000\002\011" +
    "\005\000\002\011\005\000\002\011\005\000\002\011\005" +
    "\000\002\011\003\000\002\011\004\000\002\011\003\000" +
    "\002\011\003\000\002\014\005\000\002\014\005\000\002" +
    "\014\005\000\002\014\005\000\002\014\005\000\002\014" +
    "\005\000\002\014\003\000\002\014\003\000\002\014\005" +
    "\000\002\012\005\000\002\007\005\000\002\004\007\000" +
    "\002\004\011\000\002\005\007\000\002\006\013\000\002" +
    "\015\004\000\002\015\003\000\002\016\006\000\002\016" +
    "\005\000\002\010\011" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\145\000\036\004\010\006\027\012\015\014\016\016" +
    "\013\020\007\021\033\022\030\024\011\036\012\037\026" +
    "\040\025\041\023\042\005\001\002\000\050\002\ufffb\004" +
    "\ufffb\006\ufffb\012\ufffb\014\ufffb\015\ufffb\016\ufffb\017\ufffb" +
    "\020\ufffb\021\ufffb\022\ufffb\024\ufffb\025\ufffb\026\ufffb\036" +
    "\ufffb\037\ufffb\040\ufffb\041\ufffb\042\ufffb\001\002\000\032" +
    "\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\027\uffeb\030" +
    "\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\035\053\001\002" +
    "\000\034\004\ufff5\005\063\006\064\007\066\010\065\013" +
    "\ufff5\023\ufff5\027\ufff5\030\ufff5\031\107\032\110\033\111" +
    "\034\106\001\002\000\004\012\144\001\002\000\050\002" +
    "\ufff6\004\ufff6\006\ufff6\012\ufff6\014\ufff6\015\ufff6\016\ufff6" +
    "\017\ufff6\020\ufff6\021\ufff6\022\ufff6\024\ufff6\025\ufff6\026" +
    "\ufff6\036\ufff6\037\ufff6\040\ufff6\041\ufff6\042\ufff6\001\002" +
    "\000\004\012\125\001\002\000\014\004\uffe4\013\uffe4\023" +
    "\uffe4\027\uffe4\030\uffe4\001\002\000\004\012\117\001\002" +
    "\000\050\002\ufff8\004\ufff8\006\ufff8\012\ufff8\014\ufff8\015" +
    "\ufff8\016\ufff8\017\ufff8\020\ufff8\021\ufff8\022\ufff8\024\ufff8" +
    "\025\ufff8\026\ufff8\036\ufff8\037\ufff8\040\ufff8\041\ufff8\042" +
    "\ufff8\001\002\000\020\006\027\012\015\036\012\037\026" +
    "\040\025\041\023\042\042\001\002\000\036\004\010\006" +
    "\027\012\015\014\016\016\013\020\007\021\033\022\030" +
    "\024\011\036\012\037\026\040\025\041\023\042\005\001" +
    "\002\000\014\004\ufff4\013\ufff4\023\ufff4\027\ufff4\030\ufff4" +
    "\001\002\000\004\004\100\001\002\000\040\002\076\004" +
    "\010\006\027\012\015\014\016\016\013\020\007\021\033" +
    "\022\030\024\011\036\012\037\026\040\025\041\023\042" +
    "\005\001\002\000\010\004\075\027\044\030\043\001\002" +
    "\000\034\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec\013" +
    "\uffec\023\uffec\027\uffec\030\uffec\031\uffec\032\uffec\033\uffec" +
    "\034\uffec\001\002\000\050\002\ufff9\004\ufff9\006\ufff9\012" +
    "\ufff9\014\ufff9\015\ufff9\016\ufff9\017\ufff9\020\ufff9\021\ufff9" +
    "\022\ufff9\024\ufff9\025\ufff9\026\ufff9\036\ufff9\037\ufff9\040" +
    "\ufff9\041\ufff9\042\ufff9\001\002\000\034\004\uffee\005\uffee" +
    "\006\uffee\007\uffee\010\uffee\013\uffee\023\uffee\027\uffee\030" +
    "\uffee\031\uffee\032\uffee\033\uffee\034\uffee\001\002\000\014" +
    "\004\uffe3\013\uffe3\023\uffe3\027\uffe3\030\uffe3\001\002\000" +
    "\014\006\027\012\061\040\025\041\023\042\042\001\002" +
    "\000\004\012\055\001\002\000\050\002\ufffc\004\ufffc\006" +
    "\ufffc\012\ufffc\014\ufffc\015\ufffc\016\ufffc\017\ufffc\020\ufffc" +
    "\021\ufffc\022\ufffc\024\ufffc\025\ufffc\026\ufffc\036\ufffc\037" +
    "\ufffc\040\ufffc\041\ufffc\042\ufffc\001\002\000\050\002\ufffa" +
    "\004\ufffa\006\ufffa\012\ufffa\014\ufffa\015\ufffa\016\ufffa\017" +
    "\ufffa\020\ufffa\021\ufffa\022\ufffa\024\ufffa\025\ufffa\026\ufffa" +
    "\036\ufffa\037\ufffa\040\ufffa\041\ufffa\042\ufffa\001\002\000" +
    "\004\012\035\001\002\000\042\002\uffff\004\uffff\006\uffff" +
    "\012\uffff\014\uffff\015\uffff\016\uffff\020\uffff\021\uffff\022" +
    "\uffff\024\uffff\036\uffff\037\uffff\040\uffff\041\uffff\042\uffff" +
    "\001\002\000\004\042\036\001\002\000\004\035\053\001" +
    "\002\000\004\004\040\001\002\000\020\006\027\012\015" +
    "\036\012\037\026\040\025\041\023\042\042\001\002\000" +
    "\010\004\045\027\044\030\043\001\002\000\034\004\uffeb" +
    "\005\uffeb\006\uffeb\007\uffeb\010\uffeb\013\uffeb\023\uffeb\027" +
    "\uffeb\030\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\001\002" +
    "\000\020\006\027\012\015\036\012\037\026\040\025\041" +
    "\023\042\042\001\002\000\020\006\027\012\015\036\012" +
    "\037\026\040\025\041\023\042\042\001\002\000\004\042" +
    "\036\001\002\000\004\013\047\001\002\000\036\004\010" +
    "\006\027\012\015\014\016\016\013\020\007\021\033\022" +
    "\030\024\011\036\012\037\026\040\025\041\023\042\005" +
    "\001\002\000\050\002\uffdc\004\uffdc\006\uffdc\012\uffdc\014" +
    "\uffdc\015\uffdc\016\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc" +
    "\024\uffdc\025\uffdc\026\uffdc\036\uffdc\037\uffdc\040\uffdc\041" +
    "\uffdc\042\uffdc\001\002\000\014\004\uffea\013\uffea\023\uffea" +
    "\027\uffea\030\uffea\001\002\000\014\004\uffe9\013\uffe9\023" +
    "\uffe9\027\uffe9\030\uffe9\001\002\000\020\006\027\012\015" +
    "\036\012\037\026\040\025\041\023\042\042\001\002\000" +
    "\012\004\uffe1\013\uffe1\027\044\030\043\001\002\000\020" +
    "\006\027\012\015\036\012\037\026\040\025\041\023\042" +
    "\042\001\002\000\010\013\057\027\044\030\043\001\002" +
    "\000\004\004\060\001\002\000\050\002\ufff7\004\ufff7\006" +
    "\ufff7\012\ufff7\014\ufff7\015\ufff7\016\ufff7\017\ufff7\020\ufff7" +
    "\021\ufff7\022\ufff7\024\ufff7\025\ufff7\026\ufff7\036\ufff7\037" +
    "\ufff7\040\ufff7\041\ufff7\042\ufff7\001\002\000\014\006\027" +
    "\012\061\040\025\041\023\042\042\001\002\000\034\004" +
    "\uffed\005\uffed\006\uffed\007\uffed\010\uffed\013\uffed\023\uffed" +
    "\027\uffed\030\uffed\031\uffed\032\uffed\033\uffed\034\uffed\001" +
    "\002\000\014\006\027\012\061\040\025\041\023\042\042" +
    "\001\002\000\014\006\027\012\061\040\025\041\023\042" +
    "\042\001\002\000\014\006\027\012\061\040\025\041\023" +
    "\042\042\001\002\000\014\006\027\012\061\040\025\041" +
    "\023\042\042\001\002\000\034\004\ufff1\005\ufff1\006\ufff1" +
    "\007\ufff1\010\ufff1\013\ufff1\023\ufff1\027\ufff1\030\ufff1\031" +
    "\ufff1\032\ufff1\033\ufff1\034\ufff1\001\002\000\034\004\ufff0" +
    "\005\ufff0\006\ufff0\007\ufff0\010\ufff0\013\ufff0\023\ufff0\027" +
    "\ufff0\030\ufff0\031\ufff0\032\ufff0\033\ufff0\034\ufff0\001\002" +
    "\000\034\004\ufff2\005\ufff2\006\ufff2\007\066\010\065\013" +
    "\ufff2\023\ufff2\027\ufff2\030\ufff2\031\ufff2\032\ufff2\033\ufff2" +
    "\034\ufff2\001\002\000\034\004\ufff3\005\ufff3\006\ufff3\007" +
    "\066\010\065\013\ufff3\023\ufff3\027\ufff3\030\ufff3\031\ufff3" +
    "\032\ufff3\033\ufff3\034\ufff3\001\002\000\014\005\063\006" +
    "\064\007\066\010\065\013\074\001\002\000\034\004\uffef" +
    "\005\uffef\006\uffef\007\uffef\010\uffef\013\uffef\023\uffef\027" +
    "\uffef\030\uffef\031\uffef\032\uffef\033\uffef\034\uffef\001\002" +
    "\000\050\002\ufffd\004\ufffd\006\ufffd\012\ufffd\014\ufffd\015" +
    "\ufffd\016\ufffd\017\ufffd\020\ufffd\021\ufffd\022\ufffd\024\ufffd" +
    "\025\ufffd\026\ufffd\036\ufffd\037\ufffd\040\ufffd\041\ufffd\042" +
    "\ufffd\001\002\000\004\002\001\001\002\000\042\002\000" +
    "\004\000\006\000\012\000\014\000\015\000\016\000\020" +
    "\000\021\000\022\000\024\000\036\000\037\000\040\000" +
    "\041\000\042\000\001\002\000\050\002\ufffe\004\ufffe\006" +
    "\ufffe\012\ufffe\014\ufffe\015\ufffe\016\ufffe\017\ufffe\020\ufffe" +
    "\021\ufffe\022\ufffe\024\ufffe\025\ufffe\026\ufffe\036\ufffe\037" +
    "\ufffe\040\ufffe\041\ufffe\042\ufffe\001\002\000\040\004\010" +
    "\006\027\012\015\014\016\015\102\016\013\020\007\021" +
    "\033\022\030\024\011\036\012\037\026\040\025\041\023" +
    "\042\005\001\002\000\050\002\uffe0\004\uffe0\006\uffe0\012" +
    "\uffe0\014\uffe0\015\uffe0\016\uffe0\017\uffe0\020\uffe0\021\uffe0" +
    "\022\uffe0\024\uffe0\025\uffe0\026\uffe0\036\uffe0\037\uffe0\040" +
    "\uffe0\041\uffe0\042\uffe0\001\002\000\010\013\116\027\ufff4" +
    "\030\ufff4\001\002\000\030\005\063\006\064\007\066\010" +
    "\065\013\074\027\ufff5\030\ufff5\031\107\032\110\033\111" +
    "\034\106\001\002\000\006\027\044\030\043\001\002\000" +
    "\014\006\027\012\061\040\025\041\023\042\042\001\002" +
    "\000\014\006\027\012\061\040\025\041\023\042\042\001" +
    "\002\000\014\006\027\012\061\040\025\041\023\042\042" +
    "\001\002\000\014\006\027\012\061\040\025\041\023\042" +
    "\042\001\002\000\024\004\uffe6\005\063\006\064\007\066" +
    "\010\065\013\uffe6\023\uffe6\027\uffe6\030\uffe6\001\002\000" +
    "\024\004\uffe7\005\063\006\064\007\066\010\065\013\uffe7" +
    "\023\uffe7\027\uffe7\030\uffe7\001\002\000\024\004\uffe8\005" +
    "\063\006\064\007\066\010\065\013\uffe8\023\uffe8\027\uffe8" +
    "\030\uffe8\001\002\000\024\004\uffe5\005\063\006\064\007" +
    "\066\010\065\013\uffe5\023\uffe5\027\uffe5\030\uffe5\001\002" +
    "\000\014\004\uffe2\013\uffe2\023\uffe2\027\uffe2\030\uffe2\001" +
    "\002\000\020\006\027\012\015\036\012\037\026\040\025" +
    "\041\023\042\042\001\002\000\010\013\121\027\044\030" +
    "\043\001\002\000\036\004\010\006\027\012\015\014\016" +
    "\016\013\020\007\021\033\022\030\024\011\036\012\037" +
    "\026\040\025\041\023\042\005\001\002\000\050\002\uffdf" +
    "\004\uffdf\006\uffdf\012\uffdf\014\uffdf\015\uffdf\016\uffdf\017" +
    "\123\020\uffdf\021\uffdf\022\uffdf\024\uffdf\025\uffdf\026\uffdf" +
    "\036\uffdf\037\uffdf\040\uffdf\041\uffdf\042\uffdf\001\002\000" +
    "\036\004\010\006\027\012\015\014\016\016\013\020\007" +
    "\021\033\022\030\024\011\036\012\037\026\040\025\041" +
    "\023\042\005\001\002\000\050\002\uffde\004\uffde\006\uffde" +
    "\012\uffde\014\uffde\015\uffde\016\uffde\017\uffde\020\uffde\021" +
    "\uffde\022\uffde\024\uffde\025\uffde\026\uffde\036\uffde\037\uffde" +
    "\040\uffde\041\uffde\042\uffde\001\002\000\020\006\027\012" +
    "\015\036\012\037\026\040\025\041\023\042\042\001\002" +
    "\000\010\013\127\027\044\030\043\001\002\000\004\014" +
    "\130\001\002\000\006\025\134\026\131\001\002\000\004" +
    "\023\142\001\002\000\010\015\uffda\025\uffda\026\uffda\001" +
    "\002\000\010\015\141\025\134\026\131\001\002\000\020" +
    "\006\027\012\015\036\012\037\026\040\025\041\023\042" +
    "\042\001\002\000\010\023\136\027\044\030\043\001\002" +
    "\000\036\004\010\006\027\012\015\014\016\016\013\020" +
    "\007\021\033\022\030\024\011\036\012\037\026\040\025" +
    "\041\023\042\005\001\002\000\010\015\uffd9\025\uffd9\026" +
    "\uffd9\001\002\000\010\015\uffdb\025\uffdb\026\uffdb\001\002" +
    "\000\050\002\uffd7\004\uffd7\006\uffd7\012\uffd7\014\uffd7\015" +
    "\uffd7\016\uffd7\017\uffd7\020\uffd7\021\uffd7\022\uffd7\024\uffd7" +
    "\025\uffd7\026\uffd7\036\uffd7\037\uffd7\040\uffd7\041\uffd7\042" +
    "\uffd7\001\002\000\036\004\010\006\027\012\015\014\016" +
    "\016\013\020\007\021\033\022\030\024\011\036\012\037" +
    "\026\040\025\041\023\042\005\001\002\000\010\015\uffd8" +
    "\025\uffd8\026\uffd8\001\002\000\020\006\027\012\015\036" +
    "\012\037\026\040\025\041\023\042\042\001\002\000\010" +
    "\013\146\027\044\030\043\001\002\000\036\004\010\006" +
    "\027\012\015\014\016\016\013\020\007\021\033\022\030" +
    "\024\011\036\012\037\026\040\025\041\023\042\005\001" +
    "\002\000\050\002\uffdd\004\uffdd\006\uffdd\012\uffdd\014\uffdd" +
    "\015\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd\024" +
    "\uffdd\025\uffdd\026\uffdd\036\uffdd\037\uffdd\040\uffdd\041\uffdd" +
    "\042\uffdd\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\145\000\030\002\020\003\033\004\030\005\003\006" +
    "\031\007\013\010\023\011\005\012\017\013\021\014\016" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\011\103\013\104\014\102\001\001\000\030\002\100" +
    "\003\033\004\030\005\003\006\031\007\013\010\023\011" +
    "\005\012\017\013\021\014\016\001\001\000\002\001\001" +
    "\000\002\001\001\000\026\003\076\004\030\005\003\006" +
    "\031\007\013\010\023\011\005\012\017\013\021\014\016" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\061" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\012\036" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\011" +
    "\005\013\040\014\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\005\013\051\014\016\001\001\000" +
    "\010\011\005\013\050\014\016\001\001\000\004\012\045" +
    "\001\001\000\002\001\001\000\026\003\047\004\030\005" +
    "\003\006\031\007\013\010\023\011\005\012\017\013\021" +
    "\014\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\011\005\013\053\014\016\001\001" +
    "\000\002\001\001\000\010\011\005\013\055\014\016\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\011\072\001\001\000\002\001\001\000\004\011" +
    "\071\001\001\000\004\011\070\001\001\000\004\011\067" +
    "\001\001\000\004\011\066\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\026\003\076" +
    "\004\030\005\003\006\031\007\013\010\023\011\005\012" +
    "\017\013\021\014\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\114\001\001\000\004\011\113\001\001\000\004\011\112" +
    "\001\001\000\004\011\111\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\011\005\013\117\014\016\001\001\000" +
    "\002\001\001\000\026\003\121\004\030\005\003\006\031" +
    "\007\013\010\023\011\005\012\017\013\021\014\016\001" +
    "\001\000\002\001\001\000\026\003\123\004\030\005\003" +
    "\006\031\007\013\010\023\011\005\012\017\013\021\014" +
    "\016\001\001\000\002\001\001\000\010\011\005\013\125" +
    "\014\016\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\015\132\016\131\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\016\137\001\001\000\010\011\005\013" +
    "\134\014\016\001\001\000\002\001\001\000\026\003\136" +
    "\004\030\005\003\006\031\007\013\010\023\011\005\012" +
    "\017\013\021\014\016\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\003\142\004\030\005" +
    "\003\006\031\007\013\010\023\011\005\012\017\013\021" +
    "\014\016\001\001\000\002\001\001\000\010\011\005\013" +
    "\144\014\016\001\001\000\002\001\001\000\026\003\146" +
    "\004\030\005\003\006\031\007\013\010\023\011\005\012" +
    "\017\013\021\014\016\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {
 return s.next_token(); 
    }


    scanner s;
    Map<String, Object> vars = new HashMap<>();

    public parser(scanner s){ this.s = s; 
    }
    @Override
    public void syntax_error(Symbol s) {
        // s.left guarda a LINHA
        // s.right guarda a COLUNA
        System.err.println("Erro de sintaxe na Linha " + s.left + ", Coluna " + s.right);
        
    }
    

    /* --- CLASSE AUXILIAR PARA O SWITCH --- */
    /* Armazena o par: Valor de Comparação + Código a executar */
    static class CaseObs {
        Supplier<Object> value; // null se for 'default'
        Runnable action;
        
        public CaseObs(Supplier<Object> val, Runnable act) {
            this.value = val;
            this.action = act;
        }
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= stmt_list EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable start_val = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // stmt_list ::= stmt_list stmt 
            {
              Runnable RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable l = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            RESULT = () -> {
                if (l != null) l.run();
                if (s != null) s.run();
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // stmt_list ::= stmt 
            {
              Runnable RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt_list",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // stmt ::= assignment_expr SEMI 
            {
              Runnable RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> a = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = () -> { a.get(); }; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // stmt ::= any_expr SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = () -> { e.get(); }; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // stmt ::= if_stmt 
            {
              Runnable RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable i = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = i; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // stmt ::= while_stmt 
            {
              Runnable RESULT =null;
		int wleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int wright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable w = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = w; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // stmt ::= for_stmt 
            {
              Runnable RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable f = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // stmt ::= switch_stmt 
            {
              Runnable RESULT =null;
		int swleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int swright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable sw = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = sw; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // stmt ::= block 
            {
              Runnable RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable b = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // stmt ::= PRINT LPAREN any_expr RPAREN SEMI 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
            RESULT = () -> System.out.println(e.get());
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // stmt ::= SEMI 
            {
              Runnable RESULT =null;
		 RESULT = () -> {}; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("stmt",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // any_expr ::= expr 
            {
              Supplier<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("any_expr",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // any_expr ::= bool_expr 
            {
              Supplier<Object> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Boolean> b = (Supplier<Boolean>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Object) b.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("any_expr",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // expr ::= expr PLUS expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() + (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // expr ::= expr MINUS expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() - (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // expr ::= expr TIMES expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() * (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // expr ::= expr DIV expr 
            {
              Supplier<Object> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() / (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // expr ::= LPAREN expr RPAREN 
            {
              Supplier<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // expr ::= NUMBER 
            {
              Supplier<Object> RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double n = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // expr ::= MINUS expr 
            {
              Supplier<Object> RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> -(Double)e.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr ::= STRING 
            {
              Supplier<Object> RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> s; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr ::= WORD 
            {
              Supplier<Object> RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                RESULT = () -> {
                    Object val = vars.get(nome);
                    return (val == null) ? 0 : val;
                };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // bool_expr ::= any_expr IGUAL any_expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> Objects.equals(e1.get(), e2.get()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // bool_expr ::= any_expr NOT any_expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> !Objects.equals(e1.get(), e2.get()); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // bool_expr ::= expr MENOR_QUE expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() < (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // bool_expr ::= expr MAIOR_QUE expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() > (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // bool_expr ::= expr MENOR_IGUAL expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() <= (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // bool_expr ::= expr MAIOR_IGUAL expr 
            {
              Supplier<Boolean> RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e1 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> e2 = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = () -> (Double)e1.get() >= (Double)e2.get(); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // bool_expr ::= TRUE 
            {
              Supplier<Boolean> RESULT =null;
		 RESULT = () -> true;  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // bool_expr ::= FALSE 
            {
              Supplier<Boolean> RESULT =null;
		 RESULT = () -> false; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // bool_expr ::= LPAREN bool_expr RPAREN 
            {
              Supplier<Boolean> RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Supplier<Boolean> b = (Supplier<Boolean>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = b; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bool_expr",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // assignment_expr ::= WORD GETS any_expr 
            {
              Supplier<Object> RESULT =null;
		int nomeleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int nomeright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String nome = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Supplier<Object> val = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
          RESULT = () -> {
              Object v = val.get();
              vars.put(nome, v);
              return v;
          };
      
              CUP$parser$result = parser.getSymbolFactory().newSymbol("assignment_expr",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // block ::= LBRACE stmt_list RBRACE 
            {
              Runnable RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Runnable l = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = l; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("block",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // if_stmt ::= IF LPAREN any_expr RPAREN stmt 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   Object val = e.get();
                   if (val instanceof Boolean && (Boolean)val) { s.run(); }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // if_stmt ::= IF LPAREN any_expr RPAREN stmt ELSE stmt 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int s1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int s1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Runnable s1 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int s2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int s2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s2 = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   Object val = e.get();
                   if (val instanceof Boolean && (Boolean)val) { s1.run(); } else { s2.run(); }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("if_stmt",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // while_stmt ::= WHILE LPAREN any_expr RPAREN stmt 
            {
              Runnable RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   Object val = e.get();
                   while (val instanceof Boolean && (Boolean)val) {
                       s.run();
                       val = e.get();
                   }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("while_stmt",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // for_stmt ::= FOR LPAREN assignment_expr SEMI any_expr SEMI assignment_expr RPAREN stmt 
            {
              Runnable RESULT =null;
		int initleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int initright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Supplier<Object> init = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> cond = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int stepleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int stepright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> step = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int bodyleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int bodyright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable body = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
               RESULT = () -> {
                   init.get();
                   Object val = cond.get();
                   while (val instanceof Boolean && (Boolean)val) {
                       body.run();
                       step.get();
                       val = cond.get();
                   }
               };
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("for_stmt",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // case_list ::= case_list case_item 
            {
              List<CaseObs> RESULT =null;
		int lleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int lright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<CaseObs> l = (List<CaseObs>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CaseObs i = (CaseObs)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            l.add(i);
            RESULT = l;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // case_list ::= case_item 
            {
              List<CaseObs> RESULT =null;
		int ileft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int iright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		CaseObs i = (CaseObs)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            List<CaseObs> l = new ArrayList<>();
            l.add(i);
            RESULT = l;
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // case_item ::= CASE any_expr COLON stmt 
            {
              CaseObs RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Supplier<Object> e = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            RESULT = new CaseObs(e, s);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_item",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // case_item ::= DEFAULT COLON stmt 
            {
              CaseObs RESULT =null;
		int sleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int sright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Runnable s = (Runnable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
            // Default tem 'value' null para identificar
            RESULT = new CaseObs(null, s);
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("case_item",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // switch_stmt ::= SWITCH LPAREN any_expr RPAREN LBRACE case_list RBRACE 
            {
              Runnable RESULT =null;
		int targetleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int targetright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Supplier<Object> target = (Supplier<Object>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int casesleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int casesright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		List<CaseObs> cases = (List<CaseObs>)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            RESULT = () -> {
                Object valAlvo = target.get(); // Valor do 'switch(X)'
                boolean executou = false;

                // 1. Tenta encontrar um case correspondente
                for (CaseObs c : cases) {
                    // Se não for default e os valores forem iguais
                    if (c.value != null) {
                        Object valCase = c.value.get();
                        if (Objects.equals(valAlvo, valCase)) {
                            c.action.run();
                            executou = true;
                            break; // Sai do switch após executar (Implicit Break)
                        }
                    }
                }

                // 2. Se nenhum case rodou, procura o default
                if (!executou) {
                    for (CaseObs c : cases) {
                        if (c.value == null) { // É o default
                            c.action.run();
                            break;
                        }
                    }
                }
            };
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("switch_stmt",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
