// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: calc.flex

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\4\0\1\10\1\11\1\12\6\0\12\13"+
    "\1\14\1\15\1\16\1\17\1\20\2\0\1\21\3\22"+
    "\1\23\15\22\1\24\1\25\6\22\1\0\1\26\2\0"+
    "\1\27\1\0\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\47\1\22\1\50\1\51\1\52\1\53\1\22"+
    "\1\54\1\22\1\55\1\22\1\56\1\0\1\57\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\3\1\1\3\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\14\13\1\14\1\15\1\16"+
    "\1\0\1\17\2\0\1\20\1\0\1\21\1\22\1\23"+
    "\47\13\1\0\1\24\1\25\4\13\1\26\1\27\1\13"+
    "\1\30\2\13\1\0\10\13\1\0\3\13\1\0\2\13"+
    "\1\31\1\32\1\33\1\34\2\13\1\0\1\13\1\35"+
    "\1\36\1\13\1\0\1\37\1\40\7\0\1\41";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\60\0\140\0\220\0\300\0\360\0\60"+
    "\0\60\0\u0120\0\60\0\60\0\u0150\0\u0180\0\u01b0\0\u01e0"+
    "\0\u0210\0\u0240\0\u0270\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360"+
    "\0\u0390\0\u03c0\0\u03f0\0\60\0\60\0\60\0\300\0\60"+
    "\0\u0420\0\360\0\60\0\u0450\0\60\0\60\0\60\0\u0480"+
    "\0\u04b0\0\u04e0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600"+
    "\0\u0630\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780"+
    "\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\u08a0\0\u08d0\0\u0900"+
    "\0\u0930\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50\0\u0a80"+
    "\0\u0ab0\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0\0\u0bd0\0\u01e0"+
    "\0\u01e0\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u01e0\0\u01e0\0\u0cc0"+
    "\0\u01e0\0\u0cf0\0\u0d20\0\u0d50\0\u0d80\0\u0db0\0\u0de0\0\u0e10"+
    "\0\u0e40\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30\0\u0f60\0\u0f90"+
    "\0\u0fc0\0\u0ff0\0\u1020\0\u01e0\0\u01e0\0\60\0\u01e0\0\u1050"+
    "\0\u1080\0\u10b0\0\u10e0\0\u01e0\0\u01e0\0\u1110\0\u1140\0\u01e0"+
    "\0\u01e0\0\u1170\0\u11a0\0\u11d0\0\u1200\0\u1230\0\u1260\0\u1290"+
    "\0\60";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\20\1\21\2\20\2\2\1\22\1\23\1\24\1\25"+
    "\2\20\1\26\2\20\1\27\2\20\1\30\1\20\1\31"+
    "\2\20\1\32\2\20\1\33\1\20\1\34\1\35\62\0"+
    "\1\3\74\0\1\36\40\0\7\37\1\40\16\37\1\41"+
    "\31\37\10\42\1\43\15\42\1\44\31\42\13\0\1\12"+
    "\63\0\1\45\57\0\1\46\57\0\1\47\61\0\5\20"+
    "\2\0\26\20\23\0\1\50\4\20\2\0\26\20\23\0"+
    "\5\20\2\0\25\20\1\51\23\0\5\20\2\0\13\20"+
    "\1\52\2\20\1\53\4\20\1\54\2\20\23\0\5\20"+
    "\2\0\16\20\1\55\7\20\23\0\5\20\2\0\20\20"+
    "\1\56\5\20\23\0\5\20\2\0\20\20\1\57\5\20"+
    "\23\0\5\20\2\0\1\60\25\20\23\0\5\20\2\0"+
    "\23\20\1\61\2\20\23\0\5\20\2\0\2\20\1\62"+
    "\23\20\23\0\5\20\2\0\1\63\25\20\23\0\5\20"+
    "\2\0\10\20\1\64\15\20\2\0\2\37\4\0\52\37"+
    "\2\42\4\0\52\42\21\0\3\20\1\65\1\20\2\0"+
    "\26\20\23\0\5\20\2\0\1\66\25\20\23\0\5\20"+
    "\2\0\1\67\25\20\23\0\5\20\2\0\21\20\1\70"+
    "\4\20\23\0\5\20\2\0\22\20\1\71\3\20\23\0"+
    "\5\20\2\0\13\20\1\72\12\20\23\0\5\20\2\0"+
    "\1\73\25\20\23\0\5\20\2\0\4\20\1\74\21\20"+
    "\23\0\5\20\2\0\17\20\1\75\6\20\23\0\5\20"+
    "\2\0\13\20\1\76\12\20\23\0\5\20\2\0\4\20"+
    "\1\77\21\20\23\0\5\20\2\0\14\20\1\100\11\20"+
    "\23\0\5\20\2\0\15\20\1\101\10\20\23\0\4\20"+
    "\1\102\2\0\26\20\23\0\5\20\2\0\25\20\1\103"+
    "\23\0\5\20\2\0\2\20\1\104\23\20\23\0\5\20"+
    "\2\0\22\20\1\105\3\20\23\0\5\20\2\0\22\20"+
    "\1\106\3\20\23\0\5\20\2\0\16\20\1\107\7\20"+
    "\23\0\5\20\2\0\6\20\1\110\17\20\23\0\5\20"+
    "\2\0\4\20\1\111\21\20\23\0\5\20\2\0\1\112"+
    "\25\20\23\0\5\20\2\0\22\20\1\113\3\20\23\0"+
    "\5\20\2\0\1\114\25\20\23\0\5\20\2\0\23\20"+
    "\1\115\2\20\23\0\5\20\2\0\6\20\1\116\17\20"+
    "\23\0\5\20\1\0\1\117\26\20\23\0\5\20\2\0"+
    "\1\120\25\20\23\0\5\20\2\0\12\20\1\121\13\20"+
    "\23\0\5\20\2\0\10\20\1\122\15\20\23\0\5\20"+
    "\2\0\4\20\1\123\21\20\23\0\5\20\2\0\20\20"+
    "\1\124\5\20\23\0\5\20\2\0\16\20\1\125\7\20"+
    "\23\0\5\20\2\0\15\20\1\126\10\20\23\0\5\20"+
    "\2\0\15\20\1\127\10\20\23\0\5\20\2\0\10\20"+
    "\1\130\15\20\23\0\5\20\2\0\15\20\1\131\10\20"+
    "\23\0\5\20\2\0\20\20\1\132\5\20\23\0\5\20"+
    "\2\0\2\20\1\133\23\20\26\0\1\134\54\0\5\20"+
    "\2\0\15\20\1\135\10\20\23\0\5\20\2\0\20\20"+
    "\1\136\5\20\23\0\5\20\2\0\1\20\1\137\17\20"+
    "\1\140\4\20\23\0\5\20\2\0\15\20\1\141\10\20"+
    "\23\0\5\20\2\0\5\20\1\142\20\20\23\0\5\20"+
    "\2\0\1\143\25\20\23\0\5\20\2\0\23\20\1\144"+
    "\2\20\25\0\1\145\55\0\5\20\2\0\7\20\1\146"+
    "\16\20\23\0\5\20\2\0\5\20\1\147\20\20\23\0"+
    "\5\20\2\0\16\20\1\150\7\20\23\0\5\20\1\0"+
    "\1\151\26\20\23\0\5\20\2\0\5\20\1\152\20\20"+
    "\23\0\5\20\2\0\13\20\1\153\12\20\23\0\5\20"+
    "\2\0\10\20\1\154\15\20\23\0\5\20\2\0\22\20"+
    "\1\155\3\20\23\0\1\156\57\0\5\20\2\0\1\157"+
    "\25\20\23\0\5\20\2\0\13\20\1\160\12\20\23\0"+
    "\5\20\2\0\16\20\1\161\7\20\42\0\1\162\40\0"+
    "\5\20\2\0\13\20\1\163\12\20\23\0\5\20\2\0"+
    "\25\20\1\164\23\0\5\20\2\0\25\20\1\165\23\0"+
    "\5\20\2\0\21\20\1\166\4\20\47\0\1\167\33\0"+
    "\5\20\2\0\25\20\1\170\23\0\5\20\2\0\22\20"+
    "\1\171\3\20\31\0\1\172\102\0\1\173\44\0\1\174"+
    "\54\0\1\175\52\0\1\176\101\0\1\177\50\0\1\200"+
    "\72\0\1\201\2\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[4800];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\4\1\2\11\1\1\2\11\17\1\3\11"+
    "\1\0\1\11\2\0\1\11\1\0\3\11\47\1\1\0"+
    "\14\1\1\0\10\1\1\0\3\1\1\0\4\1\1\11"+
    "\3\1\1\0\4\1\1\0\2\1\7\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.err.println("Caractere ilegal na linha " + (yyline+1) + ", coluna " + (yycolumn+1) + ": " + yytext());
            }
          // fall through
          case 34: break;
          case 2:
            { /**/
            }
          // fall through
          case 35: break;
          case 3:
            { return new Symbol(sym.LPAREN, yyline+1, yycolumn+1);
            }
          // fall through
          case 36: break;
          case 4:
            { return new Symbol(sym.RPAREN, yyline+1, yycolumn+1);
            }
          // fall through
          case 37: break;
          case 5:
            { return new Symbol(sym.NUMBER, yyline+1, yycolumn+1, Double.parseDouble(yytext()));
            }
          // fall through
          case 38: break;
          case 6:
            { return new Symbol(sym.COLON, yyline+1, yycolumn+1);
            }
          // fall through
          case 39: break;
          case 7:
            { return new Symbol(sym.SEMI, yyline+1, yycolumn+1);
            }
          // fall through
          case 40: break;
          case 8:
            { return new Symbol(sym.MENOR_QUE, yyline+1, yycolumn+1);
            }
          // fall through
          case 41: break;
          case 9:
            { return new Symbol(sym.GETS, yyline+1, yycolumn+1);
            }
          // fall through
          case 42: break;
          case 10:
            { return new Symbol(sym.MAIOR_QUE, yyline+1, yycolumn+1);
            }
          // fall through
          case 43: break;
          case 11:
            { return new Symbol(sym.WORD, yyline+1, yycolumn+1, yytext());
            }
          // fall through
          case 44: break;
          case 12:
            { return new Symbol(sym.LBRACE, yyline+1, yycolumn+1);
            }
          // fall through
          case 45: break;
          case 13:
            { return new Symbol(sym.RBRACE, yyline+1, yycolumn+1);
            }
          // fall through
          case 46: break;
          case 14:
            { return new Symbol(sym.NOT, yyline+1, yycolumn+1);
            }
          // fall through
          case 47: break;
          case 15:
            { String txt = yytext(); txt = txt.substring(1, txt.length()-1); return new Symbol(sym.STRING, yyline+1, yycolumn+1, txt);
            }
          // fall through
          case 48: break;
          case 16:
            { String txt = yytext();txt = txt.substring(1, txt.length()-1);return new Symbol(sym.STRING, yyline+1, yycolumn+1, txt);
            }
          // fall through
          case 49: break;
          case 17:
            { return new Symbol(sym.MENOR_IGUAL, yyline+1, yycolumn+1);
            }
          // fall through
          case 50: break;
          case 18:
            { return new Symbol(sym.IGUAL, yyline+1, yycolumn+1);
            }
          // fall through
          case 51: break;
          case 19:
            { return new Symbol(sym.MAIOR_IGUAL, yyline+1, yycolumn+1);
            }
          // fall through
          case 52: break;
          case 20:
            { return new Symbol(sym.WHILE, yyline+1, yycolumn+1);
            }
          // fall through
          case 53: break;
          case 21:
            { return new Symbol(sym.FALSE, yyline+1, yycolumn+1);
            }
          // fall through
          case 54: break;
          case 22:
            { return new Symbol(sym.TRUE, yyline+1, yycolumn+1);
            }
          // fall through
          case 55: break;
          case 23:
            { return new Symbol(sym.CASE, yyline+1, yycolumn+1);
            }
          // fall through
          case 56: break;
          case 24:
            { return new Symbol(sym.DEFAULT, yyline+1, yycolumn+1);
            }
          // fall through
          case 57: break;
          case 25:
            { return new Symbol(sym.FOR, yyline+1, yycolumn+1);
            }
          // fall through
          case 58: break;
          case 26:
            { return new Symbol(sym.MINUS, yyline+1, yycolumn+1);
            }
          // fall through
          case 59: break;
          case 27:
            { return new Symbol(sym.DIV, yyline+1, yycolumn+1);
            }
          // fall through
          case 60: break;
          case 28:
            { return new Symbol(sym.PRINT, yyline+1, yycolumn+1);
            }
          // fall through
          case 61: break;
          case 29:
            { return new Symbol(sym.TIMES, yyline+1, yycolumn+1);
            }
          // fall through
          case 62: break;
          case 30:
            { return new Symbol(sym.IF, yyline+1, yycolumn+1);
            }
          // fall through
          case 63: break;
          case 31:
            { return new Symbol(sym.ELSE, yyline+1, yycolumn+1);
            }
          // fall through
          case 64: break;
          case 32:
            { return new Symbol(sym.PLUS, yyline+1, yycolumn+1);
            }
          // fall through
          case 65: break;
          case 33:
            { return new Symbol(sym.SWITCH, yyline+1, yycolumn+1);
            }
          // fall through
          case 66: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
