
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int WORD = 35;
  public static final int UMINUS = 7;
  public static final int CASE = 22;
  public static final int LPAREN = 8;
  public static final int SEMI = 2;
  public static final int FOR = 18;
  public static final int MINUS = 4;
  public static final int RPAREN = 9;
  public static final int NOT = 25;
  public static final int IGUAL = 24;
  public static final int COMMA = 14;
  public static final int DIV = 6;
  public static final int PLUS = 3;
  public static final int IF = 15;
  public static final int EOF = 0;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int MAIOR_QUE = 27;
  public static final int NUMBER = 33;
  public static final int SWITCH = 21;
  public static final int LBRACK = 12;
  public static final int TIMES = 5;
  public static final int COLON = 20;
  public static final int LBRACE = 10;
  public static final int ELSE = 16;
  public static final int RBRACK = 13;
  public static final int WHILE = 17;
  public static final int DEFAULT = 23;
  public static final int RBRACE = 11;
  public static final int STRING = 34;
  public static final int GETS = 30;
  public static final int MENOR_QUE = 26;
  public static final int MENOR_IGUAL = 28;
  public static final int FALSE = 32;
  public static final int MAIOR_IGUAL = 29;
  public static final int PRINT = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "UMINUS",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "PRINT",
  "COLON",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "IGUAL",
  "NOT",
  "MENOR_QUE",
  "MAIOR_QUE",
  "MENOR_IGUAL",
  "MAIOR_IGUAL",
  "GETS",
  "TRUE",
  "FALSE",
  "NUMBER",
  "STRING",
  "WORD"
  };
}

